development:
  api_sources: 
    - '../rhodes/lib/commonAPI/'
    - '../Motorola-Extensions/lib/commonAPI/'
    - '../rhodes/res/generators/templates/api/xml_templates/'
    - '../rhoconnect-client/ext/rhoconnect-client/ext/'
  api: 'docs/en/edge/api/'
    
  index: 'rhodocs_edge'
  pdfkithost: 'localhost:9393'
jenkins:
  api_sources: 
    - '../../rhodes/workspace/lib/commonAPI/'
    - '../../Motorola-Extensions/workspace/lib/commonAPI/'
    - '../../rhodes/workspace/res/generators/templates/api/xml_templates/'
    - '../../rhoconnect-client/workspace/ext/rhoconnect-client/ext/'
  api: 'docs/en/edge/api/'
  index: 'rhodocs_edge'
  pdfkithost: 'localhost:9393'
edge:
  api: 'docs/en/edge/api/'
  index: 'rhodocs_edge'
  pdfkithost: 'edgedocs.rhomobile.com'
production:
  api: 'docs/en/edge/api/'
  index: 'rhodocs'
  pdfkithost: 'docs.rhomobile.com'