development:
  dirs:
    api: 'docs/api/'
    rhosync: 'docs/rhosync/'
    rhodes: '../rhodes/doc/'
    rhodesapi: 'docs/rhodesapi/'
    rhoelements: 'docs/rhoelements/'
    rhohub: 'docs/rhohub/'
    guides: 'docs/'
    rhoconnectapi: 'docs/rhoconnectapi/'
    rhoconnectjs: '../rhoconnect.js/doc/'
    rhoconnect: '../rhoconnect/doc/'
  index: 'rhodocs_edge'
  pdfkithost: 'localhost:9393'
jenkins:
  dirs:
    api: 'docs/api/'
    rhosync: 'docs/rhosync/'
    rhodes: '../../rhodes/workspace/doc/'
    rhodesapi: 'docs/rhodesapi/'
    rhoelements: 'docs/rhoelements/'
    rhohub: 'docs/rhohub/'
    guides: 'docs/'
    rhoconnectapi: 'docs/rhoconnectapi/'
    rhoconnectjs: '../../rhoconnect.js/workspace/doc/'
    rhoconnect: '../../rhoconnect/workspace/doc/'
  index: 'rhodocs_edge'
  pdfkithost: 'localhost:9393'
edge:
  dirs:
    api: 'docs/api/'
    rhosync: 'docs/rhosync/'
    rhodes: 'docs/rhodes/'
    rhodesapi: 'docs/rhodesapi/'
    rhoelements: 'docs/rhoelements/'
    rhohub: 'docs/rhohub/'
    guides: 'docs/'
    rhoconnectapi: 'docs/rhoconnectapi/'
    rhoconnectjs: 'docs/rhoconnectjs/'
    rhoconnect: 'docs/rhoconnect/'
  index: 'rhodocs_edge'
  pdfkithost: 'edgedocs.rhomobile.com'
production:
  dirs:
    api: 'docs/api/'
    rhosync: 'docs/rhosync/'
    rhodes: 'docs/rhodes/'
    rhodesapi: 'docs/rhodesapi/'
    rhoelements: 'docs/rhoelements/'
    rhohub: 'docs/rhohub/'
    guides: 'docs/'
    rhoconnectapi: 'docs/rhoconnectapi/'
    rhoconnectjs: 'docs/rhoconnectjs/'
    rhoconnect: 'docs/rhoconnect/'
  index: 'rhodocs'
  pdfkithost: 'docs.rhomobile.com'