development:
  api_sources: 
    - '../rhodes/lib/commonAPI/'
    - '../Motorola-Extensions/lib/commonAPI/'
    - '../rhodes/res/generators/templates/api/xml_templates/'
    - '../rhoconnect-client/ext/rhoconnect-client/ext/'
  api: 'docs/en/edge/api/'
  api_eb: 'eb/en/edge/api/'
  launchpad_eb: 'eb/en/edge/export/launchpad'

  index: 'rhodocs_edge'
  pdfkithost: 'localhost:9393'
  current_version: '4.1.0'
jenkins:
  api_sources: 
    - '../../rhodes/workspace/lib/commonAPI/'
    - '../../Motorola-Extensions/workspace/lib/commonAPI/'
    - '../../rhodes/workspace/res/generators/templates/api/xml_templates/'
    - '../../rhoconnect-client/workspace/ext/rhoconnect-client/ext/'
  api: 'docs/en/edge/api/'
  api_eb: 'eb/en/edge/api/'
  launchpad_eb: 'eb/en/edge/export/launchpad'
  index: 'rhodocs_edge'
  pdfkithost: 'localhost:9393'
  current_version: '4.1.0'
edge:
  api: 'docs/en/edge/api/'
  api_eb: 'eb/en/edge/api/'
  launchpad_eb: 'eb/en/edge/export/launchpad'
  index: 'rhodocs_edge'
  pdfkithost: 'edgedocs.rhomobile.com'
  current_version: '4.1.0'
production:
  api: 'docs/en/edge/api/'
  api_eb: 'eb/en/edge/api/'
  launchpad_eb: 'eb/en/edge/export/launchpad'
  index: 'rhodocs'
  pdfkithost: 'docs.rhomobile.com'
  current_version: '4.1.0'
