development:
  dirs:
    rhosync: '../rhosync/doc/'
    rhodes: '../rhodes/doc/'
    rhodesapi: 'docs/rhodesapi/'
    rhoelements: 'docs/rhoelements/'
    rhogallery: '../rhogallery/doc/'
    rhohub: 'docs/rhohub/'
    guides: 'docs/'
    rhoconnectjs: '../rhoconnect.js/doc/'
    rhoconnect: '../rhoconnect/doc/'
  index: 'rhodocs_edge'
  pdfkithost: 'localhost:9393'
jenkins:
  dirs:
    rhosync: '../../rhosync/workspace/doc/'
    rhodes: '../../rhodes/workspace/doc/'
    rhodesapi: 'docs/rhodesapi/'
    rhoelements: 'docs/rhoelements/'
    rhogallery: '../../rhogallery/workspace/doc/'
    rhohub: 'docs/rhohub/'
    guides: 'docs/'
    rhoconnectjs: '../../rhoconnect.js/workspace/doc/'
    rhoconnect: '../../rhoconnect/workspace/doc/'
  index: 'rhodocs_edge'
  pdfkithost: 'localhost:9393'
edge:
  dirs:
    rhosync: 'docs/rhosync/'
    rhodes: 'docs/rhodes/'
    rhodesapi: 'docs/rhodesapi/'
    rhoelements: 'docs/rhoelements/'
    rhohub: 'docs/rhohub/'
    rhogallery: 'docs/rhogallery/'
    guides: 'docs/'
    rhoconnectjs: 'docs/rhoconnectjs/'
    rhoconnect: 'docs/rhoconnect/'
  index: 'rhodocs_edge'
  pdfkithost: 'edgedocs.rhomobile.com'
production:
  dirs:
    rhosync: 'docs/rhosync/'
    rhodes: 'docs/rhodes/'
    rhodesapi: 'docs/rhodesapi/'
    rhoelements: 'docs/rhoelements/'
    rhohub: 'docs/rhohub/'
    rhogallery: 'docs/rhogallery/'
    guides: 'docs/'
    rhoconnectjs: 'docs/rhoconnectjs/'
    rhoconnect: 'docs/rhoconnect/'
  index: 'rhodocs'
  pdfkithost: 'docs.rhomobile.com'