development:
  dirs:
    rhosync: '../rhosync/doc/'
    rhodes: '../rhodes/doc/'
    rhogallery: '../rhogallery/doc/'
    rhohub: 'docs/rhohub/'
    guides: 'docs/'
    rhoconnectjs: '../rhoconnect.js/doc/'
    rhoconnect: '../rhoconnect/doc/'
  index: 'rhodocs_edge'
  pdfkithost: 'localhost:9393'
edge:
  dirs:
    rhosync: 'docs/rhosync/'
    rhodes: 'docs/rhodes/'
    rhohub: 'docs/rhohub/'
    rhogallery: 'docs/rhogallery/'
    guides: 'docs/'
    rhoconnectjs: 'docs/rhoconnectjs/'
    rhoconnect: 'docs/rhoconnect/'
  index: 'rhodocs_edge'
  pdfkithost: 'edgedocs.rhomobile.com'
  rhonav_host: http://app.staging.rhohub.com
production:
  dirs:
    rhosync: 'docs/rhosync/'
    rhodes: 'docs/rhodes/'
    rhohub: 'docs/rhohub/'
    rhogallery: 'docs/rhogallery/'
    guides: 'docs/'
    rhoconnectjs: 'docs/rhoconnectjs/'
    rhoconnect: 'docs/rhoconnect/'
  index: 'rhodocs'
  pdfkithost: 'docs.rhomobile.com'
  rhonav_host: https://app.rhohub.com