development:
  api_sources: 
    - '../rhodes/lib/commonAPI/'
    - '../Motorola-Extensions/lib/commonAPI/'
    - '../rhodes/res/generators/templates/api/xml_templates/'
    - '../rhoconnect-client/ext/rhoconnect-client/ext/'
  dirs:
    api: 'docs/api/'
    guide: 'docs/guide/'
    rhosync: 'docs/rhosync/'
    rhodes: 'docs/rhodes/'
    rhodesapi: 'docs/rhodesapi/'
    rhoelements: 'docs/rhoelements/'
    rhohub: 'docs/rhohub/'
    guides: 'docs/'
    rhoconnectapi: 'docs/rhoconnectapi/'
    rhoconnectjs: 'docs/rhoconnectjs/'
    rhoconnect: 'docs/rhoconnect/'
  index: 'rhodocs_edge'
  pdfkithost: 'localhost:9393'
jenkins:
  api_sources: 
    - '../../rhodes/workspace/lib/commonAPI/'
    - '../../Motorola-Extensions/workspace/lib/commonAPI/'
    - '../../rhodes/workspace/res/generators/templates/api/xml_templates/'
    - '../../rhoconnect-client/workspace/ext/rhoconnect-client/ext/'
  dirs:
    api: 'docs/api/'
    guide: 'docs/guide/'
    rhosync: 'docs/rhosync/'
    rhodes: '../../rhodes/workspace/doc/'
    rhodesapi: 'docs/rhodesapi/'
    rhoelements: 'docs/rhoelements/'
    rhohub: 'docs/rhohub/'
    guides: 'docs/'
    rhoconnectapi: 'docs/rhoconnectapi/'
    rhoconnectjs: '../../rhoconnect.js/workspace/doc/'
    rhoconnect: '../../rhoconnect/workspace/doc/'
  index: 'rhodocs_edge'
  pdfkithost: 'localhost:9393'
edge:
  dirs:
    api: 'docs/api/'
    guide: 'docs/guide/'
    rhosync: 'docs/rhosync/'
    rhodes: 'docs/rhodes/'
    rhodesapi: 'docs/rhodesapi/'
    rhoelements: 'docs/rhoelements/'
    rhohub: 'docs/rhohub/'
    guides: 'docs/'
    rhoconnectapi: 'docs/rhoconnectapi/'
    rhoconnectjs: 'docs/rhoconnectjs/'
    rhoconnect: 'docs/rhoconnect/'
  index: 'rhodocs_edge'
  pdfkithost: 'edgedocs.rhomobile.com'
production:
  dirs:
    api: 'docs/api/'
    guide: 'docs/guide/'
    rhosync: 'docs/rhosync/'
    rhodes: 'docs/rhodes/'
    rhodesapi: 'docs/rhodesapi/'
    rhoelements: 'docs/rhoelements/'
    rhohub: 'docs/rhohub/'
    guides: 'docs/'
    rhoconnectapi: 'docs/rhoconnectapi/'
    rhoconnectjs: 'docs/rhoconnectjs/'
    rhoconnect: 'docs/rhoconnect/'
  index: 'rhodocs'
  pdfkithost: 'docs.rhomobile.com'